<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>name</key>
		<string>Ergo</string>
		<key>scopeName</key>
		<string>source.ergo</string>
		<key>fileTypes</key>
		<array>
			<string>ergo</string>
		</array>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#modules</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#directives</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#clauses</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#goal_patterns</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#basic_patterns</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>comments</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>%:.*</string>
						<key>name</key>
						<string>comment.line.documentation.percent-colon.ergo</string>
					</dict>
					<dict>
						<key>match</key>
						<string>%.*</string>
						<key>name</key>
						<string>comment.line.percent.ergo</string>
					</dict>
				</array>
			</dict>
			<key>strings</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>'[^'\\]*(?:\\.[^'\\]*)*'</string>
						<key>name</key>
						<string>string.quoted.single.ergo</string>
					</dict>
					<dict>
						<key>match</key>
						<string>"[^"\\]*(?:\\.[^"\\]*)*"</string>
						<key>name</key>
						<string>string.quoted.double.ergo</string>
					</dict>
				</array>
			</dict>
			<key>numbers</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b\d+(\.\d+)?\b</string>
						<key>name</key>
						<string>constant.numeric.decimal.ergo</string>
					</dict>
				</array>
			</dict>
			<key>variables</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(([\p{Lu}]\w*)|(_\w*))\b</string>
						<key>name</key>
						<string>storage.term.variable.ergo</string>
					</dict>
				</array>
			</dict>
			<key>facts</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b([\p{Ll}]\w*)\b</string>
						<key>name</key>
						<string>keyword.fact.ergo</string>
					</dict>
				</array>
			</dict>
			<key>atoms</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#keywords</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\b([\p{Ll}]\w*)\b</string>
						<key>name</key>
						<string>storage.term.atom.ergo</string>
					</dict>
				</array>
			</dict>
			<key>dict_labels</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b([\p{Ll}]\w*)\b</string>
						<key>name</key>
						<string>storage.term.dict.label.ergo</string>
					</dict>
				</array>
			</dict>
			<key>complexes</key>
			<dict>
				<key>begin</key>
				<string>\b([^\s\(\):]+)\b\s*\(</string>
				<key>end</key>
				<string>\)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.term.complex.head.ergo</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>,</string>
						<key>name</key>
						<string>keyword.operator.expression.ergo</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#complex_patterns</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atoms</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#basic_patterns</string>
					</dict>
				</array>
			</dict>
			<key>goals</key>
			<dict>
				<key>begin</key>
				<string>\b([^\s\(\):]+)\b\s*\(</string>
				<key>end</key>
				<string>\)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>meta.goal.ergo</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>,</string>
						<key>name</key>
						<string>keyword.operator.expression.ergo</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#complex_patterns</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atoms</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#basic_patterns</string>
					</dict>
				</array>
			</dict>
			<key>directive_heads</key>
			<dict>
				<key>begin</key>
				<string>\b([^\s\(\):]+)\b\s*\(</string>
				<key>end</key>
				<string>\)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.directive.ergo</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#goal_patterns</string>
					</dict>
					<dict>
						<key>match</key>
						<string>,</string>
						<key>name</key>
						<string>keyword.operator.expression.ergo</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#basic_patterns</string>
					</dict>
				</array>
			</dict>
			<key>directives</key>
			<dict>
				<key>begin</key>
				<string>^\s*(:-)\s*</string>
				<key>end</key>
				<string>\s*(\.)\s*$</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.other.ergo</string>
					</dict>
				</dict>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.other.ergo</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#directive_heads</string>
					</dict>
				</array>
			</dict>
			<key>clauses</key>
			<dict>
				<key>begin</key>
				<string>^\s*(.+)\s*(:-)\s*</string>
				<key>end</key>
				<string>\s*(\.)\s*$</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#modules</string>
							</dict>
							<dict>
								<key>match</key>
								<string>,</string>
								<key>name</key>
								<string>keyword.operator.expression.ergo</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#goal_patterns</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#basic_patterns</string>
							</dict>
						</array>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.other.ergo</string>
					</dict>
				</dict>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.other.ergo</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#modules</string>
					</dict>
					<dict>
						<key>match</key>
						<string>,</string>
						<key>name</key>
						<string>keyword.operator.other.ergo</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#goal_patterns</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#basic_patterns</string>
					</dict>
				</array>
			</dict>
			<key>dicts</key>
			<dict>
				<key>begin</key>
				<string>\b(\w+)\b\s*\{</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#dict_labels</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#variables</string>
							</dict>
						</array>
					</dict>
				</dict>
				<key>end</key>
				<string>\}</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#complex_patterns</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#key_value</string>
					</dict>
					<dict>
						<key>match</key>
						<string>,</string>
						<key>name</key>
						<string>keyword.operator.expression.ergo</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atoms</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#basic_patterns</string>
					</dict>
				</array>
			</dict>
			<key>keywords</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(true|false)</string>
						<key>name</key>
						<string>keyword.other.ergo</string>
					</dict>
				</array>
			</dict>
			<key>operators</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(:-|->|;|!|@)</string>
						<key>name</key>
						<string>keyword.operator.other.ergo</string>
					</dict>
					<dict>
						<key>match</key>
						<string>([^\p{L}\d\s])</string>
						<key>name</key>
						<string>keyword.operator.expression.ergo</string>
					</dict>
				</array>
			</dict>
			<key>modules</key>
			<dict>
				<key>begin</key>
				<string>\b([\p{Ll}]\w*)\s*(:)\s*\b</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.module.ergo</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.expression.ergo</string>
					</dict>
				</dict>
			</dict>
			<key>key_value</key>
			<dict>
				<key>begin</key>
				<string>([\p{Ll}]\w*)\s*(:)</string>
				<key>end</key>
				<string>(,)?</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.term.dict.key.ergo</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.expression.ergo</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#complex_patterns</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#basic_patterns</string>
					</dict>
				</array>
			</dict>
			<key>delimiters</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>[\(\)\[\]\{\}]</string>
						<key>name</key>
						<string>meta.delimiter.ergo</string>
					</dict>
				</array>
			</dict>
			<key>atom_operators</key>
			<dict>
				<key>patterns</key>
				<array>
					<!-- Infix: Term, followed by an atom, followed by a term -->
					<dict>
						<key>match</key>
						<string>(?:(?&lt;!:-|->|-->)(?&lt;=[^\s,\.:;=]))\s+(?:(["'])(.*)\1|([\p{Ll}]\w*))\s+(?=[^\s,\.;=])</string>
						<key>name</key>
						<string>keyword.operator.expression.ergo</string>
					</dict>
				</array>
			</dict>
			<key>goal_patterns</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#goals</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#dicts</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atom_operators</string>
					</dict>
				</array>
			</dict>
			<key>complex_patterns</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#complexes</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#dicts</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atom_operators</string>
					</dict>
				</array>
			</dict>
			<key>basic_patterns</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#comments</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#delimiters</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#strings</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#numbers</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#operators</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#keywords</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#variables</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#facts</string>
					</dict>
				</array>
			</dict>
		</dict>
	</dict>
</plist>
